export const backgroundsColors = [
  { id: "bg-1", name: "Classic", color: "#f3f4f6", type: "solid" },
  { id: "bg-2", name: "Dark", color: "#1f2937", type: "solid" },
  { id: "bg-3", name: "Midnight", color: "#111827", type: "solid" },
  { id: "bg-4", name: "Ocean", color: "#0c4a6e", type: "solid" },
  { id: "bg-5", name: "Forest", color: "#064e3b", type: "solid" },
  { id: "bg-6", name: "Sunset", color: "#7c2d12", type: "solid" },
  { id: "bg-7", name: "Lavender", color: "#581c87", type: "solid" },
  { id: "bg-8", name: "Rose", color: "#9f1239", type: "solid" },
  {
    id: "bg-9",
    name: "Cosmic",
    color: "#000000",
    gradient: "linear-gradient(135deg, #0c0c2c 0%, #302b63 50%, #24243e 100%)",
    type: "gradient",
  },
  {
    id: "bg-10",
    name: "Sunrise",
    color: "#ffa500",
    gradient: "linear-gradient(to right, #ff8c00, #ff0080)",
    type: "gradient",
  },
  {
    id: "bg-11",
    name: "Northern Lights",
    color: "#3f51b5",
    gradient: "linear-gradient(to bottom, #3f51b5, #00bcd4)",
    type: "gradient",
  },
  {
    id: "bg-12",
    name: "Emerald",
    color: "#2ecc71",
    gradient: "linear-gradient(to right, #2ecc71, #27ae60)",
    type: "gradient",
  },
  {
    id: "bg-13",
    name: "Amethyst",
    color: "#9b59b6",
    gradient: "linear-gradient(to right, #9b59b6, #8e44ad)",
    type: "gradient",
  },
  {
    id: "bg-14",
    name: "Cherry",
    color: "#e74c3c",
    gradient: "linear-gradient(to right, #e74c3c, #c0392b)",
    type: "gradient",
  },
  {
    id: "bg-15",
    name: "Midnight Blue",
    color: "#2c3e50",
    gradient: "linear-gradient(to right, #2c3e50, #4ca1af)",
    type: "gradient",
  },
  {
    id: "bg-16",
    name: "Mojito",
    color: "#1abc9c",
    gradient: "linear-gradient(to right, #1abc9c, #2ecc71)",
    type: "gradient",
  },
  {
    id: "bg-17",
    name: "Sunset",
    color: "#f1c40f",
    gradient: "linear-gradient(to right, #f1c40f, #f39c12)",
    type: "gradient",
  },
  {
    id: "bg-18",
    name: "Dusk",
    color: "#e67e22",
    gradient: "linear-gradient(to right, #e67e22, #d35400)",
    type: "gradient",
  },
  {
    id: "bg-19",
    name: "Sea",
    color: "#3498db",
    gradient: "linear-gradient(to right, #3498db, #2980b9)",
    type: "gradient",
  },
  {
    id: "bg-20",
    name: "Berry",
    color: "#9b59b6",
    gradient: "linear-gradient(to right, #9b59b6, #8e44ad)",
    type: "gradient",
  },
  {
    id: "bg-21",
    name: "Forest",
    color: "#1abc9c",
    gradient: "linear-gradient(to right, #1abc9c, #16a085)",
    type: "gradient",
  },
  {
    id: "bg-22",
    name: "Candy",
    color: "#f368e0",
    gradient: "linear-gradient(to right, #f368e0, #b53471)",
    type: "gradient",
  },
  {
    id: "bg-23",
    name: "Twilight",
    color: "#222f3e",
    gradient: "linear-gradient(to right, #222f3e, #576574)",
    type: "gradient",
  },
  {
    id: "bg-24",
    name: "Apple",
    color: "#2ed573",
    gradient: "linear-gradient(to right, #2ed573, #7bed9f)",
    type: "gradient",
  },
  {
    id: "bg-25",
    name: "Ocean",
    color: "#1e3799",
    gradient: "linear-gradient(to right, #1e3799, #0c2461)",
    type: "gradient",
  },
];
